spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      default_batch_fetch_size: 1000

  logging:
    level:
      root: info
      org.hibernate.SQL: debug